services:
  caddy:
    image: docker.cnb.cool/makecnbgreatagain/rho-aias/rho-aias-caddy:latest
    container_name: caddy
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    network_mode: host
    user: root

    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

    security_opt:
      - no-new-privileges:true


    tmpfs:
      - /tmp

    volumes:
      - ./caddy/config:/etc/caddy:ro
      - ./caddy/.config:/root/.config
      - ./caddy/.local:/root/.local
      - ./logs/caddy:/logs

  rho-aias:
    image: docker.cnb.cool/makecnbgreatagain/rho-aias/rho-aias:latest
    container_name: rho-aias
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    network_mode: host
    volumes:
      - ./config:/app/config:ro
      - ./logs/rho-aias:/app/logs
      - ./data:/app/data
      # 必须要挂载目录，否则inotify无法监听文件变化
      # 挂载监听文件目录
      - ./logs/caddy:/caddy-logs:ro
      - /var/log:/var/log:ro
      # failguard依赖
      - /sys/fs/bpf:/sys/fs/bpf
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/kernel/btf:/sys/kernel/btf:ro
      - /usr/lib:/usr/lib:ro
      - /usr/lib64:/usr/lib64:ro
      - /lib:/lib:ro
      - /lib64:/lib64:ro
    command: ["--config", "/app/config/config.yml"]
    restart: unless-stopped

