services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    network_mode: host
    user: root

    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - ./logs/caddy:/logs

  rho-aias:
    build: .
    container_name: rho-aias
    environment:
      - TZ=Asia/Shanghai
    privileged: false
    cap_drop:
      - ALL
    cap_add:
      - CAP_BPF
      - CAP_PERFMON
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    network_mode: host
    volumes:
      - ./config.yml:/app/config/config.yml:ro
      - ./logs/rho-aias:/app/logs
      - ./data:/app/data
      - ./logs/caddy:/caddy-logs:ro
      - /var/log/auth.log:/var/log/auth.log:ro
    command: ["--config", "/app/config/config.yml"]
    restart: unless-stopped

volumes:
  caddy_data:
