// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpfs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpBlockValue struct {
	_          structs.HostLayout
	SourceMask uint32
	Priority   uint32
	Expiry     uint64
}

type xdpEventConfig struct {
	_          structs.HostLayout
	Enabled    uint32
	SampleRate uint32
	Padding    [2]uint32
}

type xdpGeoConfig struct {
	_       structs.HostLayout
	Enabled uint32
	Mode    uint32
	Padding uint32
}

type xdpIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type xdpIpv4TrieKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type xdpIpv6TrieKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      xdpIn6Addr
}

type xdpPacketInfo struct {
	_         structs.HostLayout
	SrcIp     uint32
	DstIp     uint32
	SrcIpv6   [4]uint32
	DstIpv6   [4]uint32
	EthProto  uint16
	PktSize   uint32
	MatchType uint32
}

// loadXdp returns the embedded CollectionSpec for xdp.
func loadXdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp: %w", err)
	}

	return spec, err
}

// loadXdpObjects loads xdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpObjects
//	*xdpPrograms
//	*xdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpSpecs struct {
	xdpProgramSpecs
	xdpMapSpecs
	xdpVariableSpecs
}

// xdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpProgramSpecs struct {
	XdpProg *ebpf.ProgramSpec `ebpf:"xdp_prog"`
}

// xdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpMapSpecs struct {
	BlockIpv4CidrTrie *ebpf.MapSpec `ebpf:"block_ipv4_cidr_trie"`
	BlockIpv4List     *ebpf.MapSpec `ebpf:"block_ipv4_list"`
	BlockIpv6CidrTrie *ebpf.MapSpec `ebpf:"block_ipv6_cidr_trie"`
	BlockIpv6List     *ebpf.MapSpec `ebpf:"block_ipv6_list"`
	EventConfig       *ebpf.MapSpec `ebpf:"event_config"`
	Events            *ebpf.MapSpec `ebpf:"events"`
	GeoConfig         *ebpf.MapSpec `ebpf:"geo_config"`
	GeoIpv4Whitelist  *ebpf.MapSpec `ebpf:"geo_ipv4_whitelist"`
	Scratch           *ebpf.MapSpec `ebpf:"scratch"`
}

// xdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpVariableSpecs struct {
}

// xdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpObjects struct {
	xdpPrograms
	xdpMaps
	xdpVariables
}

func (o *xdpObjects) Close() error {
	return _XdpClose(
		&o.xdpPrograms,
		&o.xdpMaps,
	)
}

// xdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpMaps struct {
	BlockIpv4CidrTrie *ebpf.Map `ebpf:"block_ipv4_cidr_trie"`
	BlockIpv4List     *ebpf.Map `ebpf:"block_ipv4_list"`
	BlockIpv6CidrTrie *ebpf.Map `ebpf:"block_ipv6_cidr_trie"`
	BlockIpv6List     *ebpf.Map `ebpf:"block_ipv6_list"`
	EventConfig       *ebpf.Map `ebpf:"event_config"`
	Events            *ebpf.Map `ebpf:"events"`
	GeoConfig         *ebpf.Map `ebpf:"geo_config"`
	GeoIpv4Whitelist  *ebpf.Map `ebpf:"geo_ipv4_whitelist"`
	Scratch           *ebpf.Map `ebpf:"scratch"`
}

func (m *xdpMaps) Close() error {
	return _XdpClose(
		m.BlockIpv4CidrTrie,
		m.BlockIpv4List,
		m.BlockIpv6CidrTrie,
		m.BlockIpv6List,
		m.EventConfig,
		m.Events,
		m.GeoConfig,
		m.GeoIpv4Whitelist,
		m.Scratch,
	)
}

// xdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpVariables struct {
}

// xdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpPrograms struct {
	XdpProg *ebpf.Program `ebpf:"xdp_prog"`
}

func (p *xdpPrograms) Close() error {
	return _XdpClose(
		p.XdpProg,
	)
}

func _XdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_bpfel.o
var _XdpBytes []byte
